# conda env create -f conda-env_gnn-urban-form_cpu.yml
# conda activate gnn-urban-form-cpu
#
name: gnn-urban-form-cpu
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python
  - networkx
  - osmnx
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pyg
  - colormaps
  - seaborn
  - plotly
  - dash
  - hdbscan
