# conda env create --file=conda-env_pyg-2-6-1_cuda.yml
# conda activate pyg-2-6-1_cuda
#
name: pyg-2-6-1_cuda
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
  - rapidsai
dependencies:
  # Python
  - conda-forge::python
  # CUDA
  - nvidia::cuda=12.1
  # Pytorch
  - pytorch::pytorch=2.4
  - pytorch::torchvision
  - pytorch::torchaudio 
  - pytorch::pytorch-cuda=12.1
  - conda-forge::lightning
  # Pytorch Geometric
  - pyg::pyg=2.6.1
  - pyg::pytorch-sparse 
  - pyg::pytorch-scatter
  # Other
  - rapidsai::rapids
  - conda-forge::tensorboard
  - conda-forge::fastparquet  
  - conda-forge::geopandas
  - conda-forge::pysal
  - conda-forge::networkx
  - conda-forge::osmnx
  - conda-forge::clustergram
  - conda-forge::hdbscan
  - conda-forge::umap-learn
  - conda-forge::seaborn
  - plotly::plotly
  - plotly::dash
  # Jupyter notebooks
  - conda-forge::jupyterlab
  - conda-forge::notebook

