# module load gcc/12.3.0
# module load cuda12.1/toolkit
# module load cudnn8.9-cuda12.1
# conda env create -f conda-env_gnn-urban-form_cuda-12-1.yml
# conda activate gnn-urban-form-cuda-12-1
#
# cd $CONDA_PREFIX
# mkdir -p ./etc/conda/activate.d
# mkdir -p ./etc/conda/deactivate.d
# touch ./etc/conda/activate.d/env_vars.sh
# touch ./etc/conda/deactivate.d/env_vars.sh
#
# gedit ./etc/conda/activate.d/env_vars.sh
#
# ---
# #!/bin/sh
#
# module purge
# module load gcc/12.3.0
# module load cuda12.1/toolkit
# module load cudnn8.9-cuda12.1
#
# export LD_LIBRARY_PATH=~/miniconda3/envs/gnn-urban-form-cuda-12-1/lib/:$LD_LIBRARY_PATH
#
# ---
#
# gedit ./etc/conda/deactivate.d/env_vars.sh
#
# ---
# #!/bin/sh
#
# module purge
#
# ---
#
name: gnn-urban-form-cuda-12-1
channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyg
dependencies:
  - python
  - networkx
  - osmnx
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio 
  - pytorch::pytorch-cuda=12.1
  - pyg::pyg
  - colormaps
  - seaborn
  - plotly
  - dash
  - hdbscan
  - umap-learn
