# conda env create -f conda-env_gnn-urban-form.yml
# conda activate gnn-urban-form
# pip install torch==1.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
# pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
# pip install seaborn
# pip install colormaps
# pip install plotly==5.15.0
#
name: gnn-urban-form
channels:
  - conda-forge
dependencies:
  - python=3.10
  - networkx=3.0
  - osmnx=1.3.0
