# conda env create -f conda-env_gnn-urban-form.yml
# conda activate gnn-urban-form
# pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv torch_geometric -f https://data.pyg.org/whl/torch-1.13.0+cpu.html
#
name: gnn-urban-form
channels:
  - conda-forge
dependencies:
  - python=3.10
  - networkx=3.0
  - osmnx=1.3.0
  - jupyterlab
  - pytorch=1.13.1
